apiVersion: v1
kind: Pod
metadata:
  name: httpd
  namespace: default
spec:
  containers:
    - name: httpd
      image: httpd:2.4
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - name: httpdconf
        mountPath: /usr/local/apache2/conf/httpd.conf
        subPath: httpd.conf
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 1
        periodSeconds: 3
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 1
        periodSeconds: 3
      startupProbe:
        httpGet:
          path: /
          port: 80
        failureThreshold: 60
        periodSeconds: 5
  volumes:
  - name: httpdconf
    configMap:
      name: httpdconfigmap
