apiVersion: v1
kind: Pod
metadata:
  name: tomcat-detector
  namespace: default
spec:
  serviceAccountName: internal-kubectl
  containers:
    - name: tomcat-detector
      image: tomcat_detector:alpha
      imagePullPolicy: IfNotPresent
      tty: true
